builds:
  # List of builds
  - # First Build
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: "-s -w -X github.com/elfranne/haproxy_runtimeapi_exporter/version.version={{.Version}} -X github.com/elfranne/haproxy_runtimeapi_exporter/version.commit={{.Commit}} -X github.com/elfranne/haproxy_runtimeapi_exporter/version.date={{.Date}}"
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    targets:
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz